server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: excelreading
          uri: http://localhost:8082/
          predicates:
            - Path=/excelreading/**
        - id: dataexcelreading
          uri: http://localhost:8083/
          predicates:
            - Path=/dataexcel/**